name: Check

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: read

jobs:
 
  check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: PHP Linter
      run: php -l *
    - name: PHPStan Static Analysis
      uses: php-actions/phpstan@v3
      with:
        path: .
